import ctypes


# consts
HASH_RING_OK = 0
HASH_RING_ERR = 1

HASH_FUNCTION = ctypes.c_uint8
HASH_FUNCTION_SHA1 = 1
HASH_FUNCTION_MD5 = 2

HASH_RING_DEBUG = 1

HASH_RING_MODE_NORMAL = 1
HASH_RING_MODE_LIBMEMCACHED_COMPAT = 2
HASH_MODE = ctypes.c_uint8
